cat <<EOF | kubectl apply -f -
# # Orginial source of the configuration file: https://github.com/elastic/cloud-on-k8s/blob/2.9/config/samples/kibana/kibana_es.yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 7.17.12
  count: 1
  elasticsearchRef:
    name: "elastic-iot"
  #http:
  #  service:
  #    spec:
  #      type: LoadBalancer
  # this shows how to customize the Kibana pod
  # with labels and resource limits
  podTemplate:
    metadata:
      labels:
        foo: bar
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 2Gi
            cpu: 1
EOF